export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';

export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY';

export const EXPAND_ALL = 'EXPAND_ALL';
